### PR TITLE
Add support for ActiveModel Validator

### PR DESCRIPTION
**Pull request by thukim**
Hi Morra,

It would be nice if we can support this IRD number validator for ActiveModel, so I made these commits to add it in. I have also updated the README file with this change and bumped the version up.

Please have a look and let me know if you want to change anything.

Have a good day!

Kimmie

### CODE REVIEW

**Comment by td512** [comment]
I do apologize, I've been without a PC for a bit. I'm pulling this down now to test

**Comment by td512** [comment]
Hey @thukim, would you mind giving a brief description of what exactly this does? I'm not entirely sure why we need ActiveRecord support

**Comment by td512** [comment]
Additionally, would this not make ActiveRecord a requirement to be able to use the gem?

**Comment by td512** [comment]
@thukim just checking to see if you could answer the question just up there ^

**Comment by thukim** [comment]
Hi @td512 sorry for this late reply, I have been busy with my project that have not had time to check this until now.
This is just ActiveModel Validation, not ActiveRecord. And it is not a requirement to be able to use this gem. It is actually an addition to the gem that, for users who use ActiveModel, they will be able to apply the gem easily in their app for ird validation by just 1 line, without having to add any other files (as I added in this PR) to make it work. 
Please let me know if this doesnt answer your questions or you have any other questions regarding this. Have a good day!

**Review by td512 — APPROVED** [review]
Looking good. I'll merge this in now, build the gem, and publish it in a few hours. Really sorry for the delay @thukim. Merry Christmas!

**Pull request merged**
